@echo off
rem Eventually this file will be auto-generated by the setup script.
rem "0.0.0.0" does *NOT* need to be changed and is there because
rem --url_get and --url_post need to be set to *something* for http
rem support to start, the actual address is set on each request.
EmuHawk.exe --url_get=https://0.0.0.0 --url_post=https://0.0.0.0
exit